name: Test Project
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: install Node Js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependency
              run: npm ci
            - name: run test
              run: npm test
    Deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: install Node Js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependency
              run: npm ci
            - name: build project
              run: npm run build
            - name: deploy
              run: echo "deployed"